// <auto-generated/>
using System.Windows.Controls;

namespace GroupMeClient.WpfUI.Views.Controls
{
    /// <summary>
    /// Interaction logic for GroupControl.xaml.
    /// </summary>
    public partial class GroupControl : UserControl
    {
        public GroupControl()
        {
            this.InitializeComponent();
        }
    }
}
