//<auto-generated />

using System.Windows.Controls;

namespace GroupMeClient.Wpf.Views.Controls
{
    /// <summary>
    /// Interaction logic for LoadingControl.xaml
    /// </summary>
    public partial class LoadingControl : UserControl
    {
        public LoadingControl()
        {
            this.InitializeComponent();
        }
    }
}
