// <auto-generated/>

using System.Windows.Controls;

namespace GroupMeClient.Views.Controls
{
    /// <summary>
    /// Interaction logic for ManageReposControl.xaml.
    /// </summary>
    public partial class ManageReposControl : UserControl
    {
        public ManageReposControl()
        {
            this.InitializeComponent();
        }
    }
}
