//<auto-generated />

using System.Windows.Controls;

namespace GroupMeClient.Wpf.Views.Controls
{
    /// <summary>
    /// Interaction logic for GroupControl.xaml
    /// </summary>
    public partial class MessageControl : UserControl
    {
        public MessageControl()
        {
            this.InitializeComponent();
        }
    }
}
