//<auto-generated />

using System.Windows.Controls;

namespace GroupMeClient.Wpf.Views.Controls
{
    /// <summary>
    /// Interaction logic for MessageEffectsControl.xaml
    /// </summary>
    public partial class MessageEffectsControl : UserControl
    {
        public MessageEffectsControl()
        {
            this.InitializeComponent();
        }
    }
}
