//<auto-generated/>

using System.Windows.Controls;

namespace GroupMeClient.WpfUI.Views.Controls
{
    /// <summary>
    /// Interaction logic for PaginatedMessagesControl.xaml
    /// </summary>
    public partial class PaginatedMessagesControl : UserControl
    {
        public PaginatedMessagesControl()
        {
            this.InitializeComponent();
        }
    }
}
