//<auto-generated/>

using System.Windows.Controls;

namespace GroupMeClient.Wpf.Views.Controls
{
    /// <summary>
    /// Interaction logic for Popup.xaml
    /// </summary>
    public partial class Popup : UserControl
    {
        public Popup()
        {
            this.InitializeComponent();
        }
    }
}
