// <auto-generated/>
using System.Windows.Controls;

namespace GroupMeClient.Views.Controls
{
    /// <summary>
    /// Interaction logic for ViewImageControl.xaml
    /// </summary>
    public partial class ViewImageControl : UserControl
    {
        public ViewImageControl()
        {
            this.InitializeComponent();
        }
    }
}
