//<auto-generated />

using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace GroupMeClient.AvaloniaUI.Views
{
    public partial class ChatsView : UserControl
    {
        public ChatsView()
        {
            InitializeComponent();
        }
    }
}
