//<auto-generated/>

using System.Windows.Controls;

namespace GroupMeClient.WpfUI.Views.Controls
{
    /// <summary>
    /// Interaction logic for InlineReadSentMarkerControl.xaml.
    /// </summary>
    public partial class InlineReadSentMarkerControl : UserControl
    {
        public InlineReadSentMarkerControl()
        {
            this.InitializeComponent();
        }
    }
}
