// <auto-generated/>

using System.Windows.Controls;

namespace GroupMeClient.WpfUI.Views.Controls
{
    /// <summary>
    /// Interaction logic for SendImageControl.xaml.
    /// </summary>
    public partial class SendImageControl : UserControl
    {
        public SendImageControl()
        {
            this.InitializeComponent();
        }
    }
}
