// <auto-generated/>

using System.Windows.Controls;

namespace GroupMeClient.WpfUI.Views.Controls
{
    /// <summary>
    /// Interaction logic for SendFileControl.xaml
    /// </summary>
    public partial class SendFileControl : UserControl
    {
        public SendFileControl()
        {
            this.InitializeComponent();
        }
    }
}
