// <auto-generated/>

using System.Windows.Controls;

namespace GroupMeClient.WpfUI.Views.Controls
{
    /// <summary>
    /// Interaction logic for UpdatePluginsControl.xaml.
    /// </summary>
    public partial class UpdatePluginsControl : UserControl
    {
        public UpdatePluginsControl()
        {
            this.InitializeComponent();
        }
    }
}
