// <auto-generated/>

using System.Windows.Controls;

namespace GroupMeClient.WpfUI.Views.Controls
{
    /// <summary>
    /// Interaction logic for ViewReleaseNotesControl.xaml.
    /// </summary>
    public partial class ViewReleaseNotesControl : UserControl
    {
        public ViewReleaseNotesControl()
        {
            this.InitializeComponent();
        }
    }
}
