// <auto-generated/>

using System.Windows;
using GroupMeClient.WpfUI.Extensions;

namespace GroupMeClient.WpfUI
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : GMDCWindow
    {
        public MainWindow()
        {
        }
    }
}
