// <auto-generated/>

using Avalonia;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Markup.Xaml;
using GroupMeClient.Core;
using GroupMeClient.Core.Services;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Toolkit.Mvvm.DependencyInjection;
using System;
using System.IO;

namespace GroupMeClient.AvaloniaUI
{
    public partial class App : Application
    {
        private readonly IHost host;

        public App()
        {
            Directory.CreateDirectory(DataRoot);

            var clientIdentity = new Core.Services.KnownClients.GMDCA();
            StartupParams = new Core.StartupExtensions.StartupParameters()
            {
                ClientIdentity = clientIdentity,
                CacheFilePath = CachePath,
                PersistFilePath = PersistPath,
                SettingsFilePath = SettingsPath,
                PluginPath = PluginsPath,
            };

            this.host = new HostBuilder()
                .ConfigureServices((hostContext, services) =>
                {
                    services.UseGMDCCoreServices(StartupParams);
                    services.UseGMDCCoreViewModels();
                    services.UseGMDCAvalonia();
                })
                .ConfigureLogging(logging =>
                {
                    logging.ClearProviders();
                })
                .Build();

            Ioc.Default.ConfigureServices(this.host.Services);
        }

        /// <summary>
        /// Gets the AUMID identifier used for Windows.
        /// </summary>
        public static string ApplicationId => "com.squirrel.GroupMeDesktopClient.GroupMeClientAvalonia";

        /// <summary>
        /// Gets the data root for the GMDC/WPF Application.
        /// </summary>
        public static string DataRoot => Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "MicroCube", "GroupMe Desktop Client");

        /// <summary>
        /// Gets the name of the settings file for the GMDC/Avalonia application.
        /// </summary>
        public static string SettingsPath => Path.Combine(DataRoot, "settings.json");

        /// <summary>
        /// Gets the cache database file path for the GMDC/Avalonia application.
        /// </summary>
        public static string CachePath => Path.Combine(DataRoot, "cache.db");

        /// <summary>
        /// Gets the persist database file path for the GMDC/Avalonia application.
        /// </summary>
        public static string PersistPath => Path.Combine(DataRoot, "persist.db");

        /// <summary>
        /// Gets the image caching folder path for the GMDC/Avalonia application.
        /// </summary>
        public static string ImageCachePath => Path.Combine(DataRoot, "ImageCache");

        /// <summary>
        /// Gets the plugin directory for the GMDC/Avalonia application.
        /// </summary>
        public static string PluginsPath => Path.Combine(DataRoot, "Plugins");

        /// <summary>
        /// Gets the themes directory for the GMDC/Avalonia application.
        /// </summary>
        public static string ThemesPath => Path.Combine(DataRoot, "Themes");

        /// <summary>
        /// Gets or sets the GMDC application parameters required to start this instance of GMDC.
        /// </summary>
        public static Core.StartupExtensions.StartupParameters StartupParams { get; set; }

        public override void Initialize()
        {
            AvaloniaXamlLoader.Load(this);
        }

        public override void OnFrameworkInitializationCompleted()
        {
            if (this.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
            {
                desktop.MainWindow = Program.CreateMainWindow();

                // Initialize the theme engine now that the UI has been defined
                var themeService = Ioc.Default.GetRequiredService<IThemeService>();
                themeService.Initialize();
            }

            base.OnFrameworkInitializationCompleted();
        }
    }
}
