// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace GroupMeClient.Core.Caching.MigrationsCache
{
    public partial class HiddenMessageSupport : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "HiddenMessages",
                columns: table => new
                {
                    MessageId = table.Column<string>(nullable: false),
                    ConversationId = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HiddenMessages", x => x.MessageId);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "HiddenMessages");
        }
    }
}
