// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace GroupMeClient.Core.Caching.MigrationsCache
{
    public partial class AddGroupChatMetadata : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "GroupMetadata",
                columns: table => new
                {
                    Id = table.Column<string>(nullable: false),
                    Name = table.Column<string>(nullable: true),
                    PhoneNumber = table.Column<string>(nullable: true),
                    Type = table.Column<string>(nullable: true),
                    Description = table.Column<string>(nullable: true),
                    ImageUrl = table.Column<string>(nullable: true),
                    CreatedAtUnixTime = table.Column<int>(nullable: false),
                    UpdatedAtUnixTime = table.Column<int>(nullable: false),
                    OfficeMode = table.Column<bool>(nullable: false),
                    MutedUntilUnixTime = table.Column<long>(nullable: true),
                    ShareUrl = table.Column<string>(nullable: true),
                    MaxMembers = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GroupMetadata", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Member",
                columns: table => new
                {
                    Id = table.Column<string>(nullable: false),
                    UserId = table.Column<string>(nullable: true),
                    Nickname = table.Column<string>(nullable: true),
                    ImageUrl = table.Column<string>(nullable: true),
                    AvatarUrl = table.Column<string>(nullable: true),
                    Muted = table.Column<bool>(nullable: false),
                    Autokicked = table.Column<bool>(nullable: false),
                    Roles = table.Column<string>(nullable: true),
                    Name = table.Column<string>(nullable: true),
                    GroupId = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Member", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Member_GroupMetadata_GroupId",
                        column: x => x.GroupId,
                        principalTable: "GroupMetadata",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "ChatMetadata",
                columns: table => new
                {
                    Id = table.Column<string>(nullable: false),
                    OtherUserId = table.Column<string>(nullable: true),
                    CreatedAtUnixTime = table.Column<int>(nullable: false),
                    UpdatedAtUnixTime = table.Column<int>(nullable: false),
                    TotalMessageCount = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ChatMetadata", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ChatMetadata_Member_OtherUserId",
                        column: x => x.OtherUserId,
                        principalTable: "Member",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ChatMetadata_OtherUserId",
                table: "ChatMetadata",
                column: "OtherUserId");

            migrationBuilder.CreateIndex(
                name: "IX_Member_GroupId",
                table: "Member",
                column: "GroupId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ChatMetadata");

            migrationBuilder.DropTable(
                name: "Member");

            migrationBuilder.DropTable(
                name: "GroupMetadata");
        }
    }
}
