//<auto-generated />

using System.Windows.Controls;

namespace GroupMeClient.Views
{
    /// <summary>
    /// XAML Code Begind for ChatsView
    /// </summary>
    public partial class ChatsView : UserControl
    {
        public ChatsView()
        {
            this.InitializeComponent();
        }
    }
}
