// <auto-generated />

using System.Windows.Controls;

namespace GroupMeClient.Wpf.Views
{
    public partial class SettingsView : UserControl
    {
        public SettingsView()
        {
            this.InitializeComponent();
        }
    }
}
