// <auto-generated/>

using System.Windows.Controls;

namespace GroupMeClient.Views
{
    /// <summary>
    /// Interaction logic for StarsView.xaml.
    /// </summary>
    public partial class StarsView : UserControl
    {
        public StarsView()
        {
            this.InitializeComponent();
        }
    }
}
