// <auto-generated />
using System.Windows.Controls;

namespace GroupMeClient.Views
{
    public partial class UpdatingView : UserControl
    {
        public UpdatingView()
        {
            this.InitializeComponent();
        }
    }
}
