// <auto-generated/>

using System.Windows.Controls;

namespace GroupMeClient.Views.Controls.Attachments
{
    /// <summary>
    /// Interaction logic for FileAttachmentControl.xaml
    /// </summary>
    public partial class FileAttachmentControl : UserControl
    {
        public FileAttachmentControl()
        {
            this.InitializeComponent();
        }
    }
}
