//<auto-generated/>

using System.Windows.Controls;

namespace GroupMeClient.Views.Controls.Attachments
{
    /// <summary>
    /// Interaction logic for RepliedMessageControl.xaml.
    /// </summary>
    public partial class RepliedMessageControl : UserControl
    {
        public RepliedMessageControl()
        {
            this.InitializeComponent();
        }
    }
}
