// <auto-generated/>
using System.Windows.Controls;

namespace GroupMeClient.Plugins.Views
{
    /// <summary>
    /// Interaction logic for GroupInfoControl.xaml
    /// </summary>
    public partial class GroupInfoControl : UserControl
    {
        public GroupInfoControl()
        {
            this.InitializeComponent();
        }
    }
}
