// <auto-generated/>
using System.Windows.Controls;

namespace GroupMeClient.Plugins.Views
{
    /// <summary>
    /// Interaction logic for ImageDetailsControl.xaml
    /// </summary>
    public partial class ImageDetailsControl : UserControl
    {
        public ImageDetailsControl()
        {
            this.InitializeComponent();
        }
    }
}
