//<auto-generated/>

using System.Windows.Controls;

namespace GroupMeClient.WpfUI.Plugins.Views
{
    /// <summary>
    /// Interaction logic for MultiLikeControl.xaml
    /// </summary>
    public partial class MultiLikeControl : UserControl
    {
        public MultiLikeControl()
        {
            this.InitializeComponent();
        }
    }
}
