//<auto-generated />

using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace GroupMeClient.AvaloniaUI.Views.Controls
{
    /// <summary>
    /// Interaction logic for AvatarControl.xaml
    /// </summary>
    public partial class AvatarControl : UserControl
    {
        public AvatarControl()
        {
            this.InitializeComponent();
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }
}
