//<auto-generated />

using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace GroupMeClient.AvaloniaUI.Views.Controls
{
    public partial class MessageEffectsControl : UserControl
    {
        public MessageEffectsControl()
        {
            this.InitializeComponent();
        }
    }
}
