// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace GroupMeClient.Core.Caching.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "IndexStatus",
                columns: table => new
                {
                    Id = table.Column<string>(nullable: false),
                    LastIndexedId = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_IndexStatus", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Messages",
                columns: table => new
                {
                    Id = table.Column<string>(nullable: false),
                    SourceGuid = table.Column<string>(nullable: true),
                    RecipientId = table.Column<string>(nullable: true),
                    CreatedAtUnixTime = table.Column<int>(nullable: false),
                    UserId = table.Column<string>(nullable: true),
                    GroupId = table.Column<string>(nullable: true),
                    ConversationId = table.Column<string>(nullable: true),
                    ChatId = table.Column<string>(nullable: true),
                    Name = table.Column<string>(nullable: true),
                    AvatarUrl = table.Column<string>(nullable: true),
                    Text = table.Column<string>(nullable: true),
                    FavoritedBy = table.Column<string>(nullable: true),
                    SenderType = table.Column<string>(nullable: true),
                    Platform = table.Column<string>(nullable: true),
                    Attachments = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Messages", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Messages_ConversationId",
                table: "Messages",
                column: "ConversationId");

            migrationBuilder.CreateIndex(
                name: "IX_Messages_GroupId",
                table: "Messages",
                column: "GroupId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "IndexStatus");

            migrationBuilder.DropTable(
                name: "Messages");
        }
    }
}
