// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace GroupMeClient.Core.Caching.Migrations
{
    public partial class StarMessageSupport : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "StarredMessages",
                columns: table => new
                {
                    MessageId = table.Column<string>(nullable: false),
                    ConversationId = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_StarredMessages", x => x.MessageId);
                });

            migrationBuilder.CreateIndex(
                name: "IX_StarredMessages_ConversationId",
                table: "StarredMessages",
                column: "ConversationId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "StarredMessages");
        }
    }
}
