// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace GroupMeClient.Core.Caching.MigrationsPersist
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "HiddenMessages",
                columns: table => new
                {
                    MessageId = table.Column<string>(nullable: false),
                    ConversationId = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HiddenMessages", x => x.MessageId);
                });

            migrationBuilder.CreateTable(
                name: "IndexStatus",
                columns: table => new
                {
                    Id = table.Column<string>(nullable: false),
                    LastIndexedId = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_IndexStatus", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "StarredMessages",
                columns: table => new
                {
                    MessageId = table.Column<string>(nullable: false),
                    ConversationId = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_StarredMessages", x => x.MessageId);
                });

            migrationBuilder.CreateIndex(
                name: "IX_HiddenMessages_ConversationId",
                table: "HiddenMessages",
                column: "ConversationId");

            migrationBuilder.CreateIndex(
                name: "IX_StarredMessages_ConversationId",
                table: "StarredMessages",
                column: "ConversationId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "HiddenMessages");

            migrationBuilder.DropTable(
                name: "IndexStatus");

            migrationBuilder.DropTable(
                name: "StarredMessages");
        }
    }
}
