// <auto-generated/>

using Microsoft.EntityFrameworkCore.Migrations;

namespace GroupMeClient.Core.Caching.MigrationsPersist
{
    public partial class AddRecoveryState : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "RecoveryStates",
                columns: table => new
                {
                    WindowId = table.Column<int>(nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    OpenChats = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RecoveryStates", x => x.WindowId);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "RecoveryStates");
        }
    }
}
