//<auto-generated/>

using Microsoft.EntityFrameworkCore.Migrations;

namespace GroupMeClient.Core.Caching.MigrationsPersist
{
    public partial class AddMessageIdIndex : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateIndex(
                name: "IX_StarredMessages_MessageId",
                table: "StarredMessages",
                column: "MessageId");

            migrationBuilder.CreateIndex(
                name: "IX_HiddenMessages_MessageId",
                table: "HiddenMessages",
                column: "MessageId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_StarredMessages_MessageId",
                table: "StarredMessages");

            migrationBuilder.DropIndex(
                name: "IX_HiddenMessages_MessageId",
                table: "HiddenMessages");
        }
    }
}
