//<auto-generated />

using System.Windows.Controls;

namespace GroupMeClient.Notifications.Display.WpfToast
{
    /// <summary>
    /// Interaction logic for ToastHolder.xaml
    /// </summary>
    public partial class ToastHolder : UserControl
    {
        public ToastHolder()
        {
            this.InitializeComponent();
        }
    }
}
