// <auto-generated/>

namespace GroupMeClient.Notifications.Display.WpfToast
{
    /// <summary>
    /// Interaction logic for ToastDisplayPart.xaml.
    /// </summary>
    public partial class ToastNotification
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ToastNotification"/> class.
        /// </summary>
        public ToastNotification()
        {
            this.InitializeComponent();
        }
    }
}
