//<auto-generated/>

using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace GroupMeClient.AvaloniaUI.Views.Controls.Attachments
{
    public class FileAttachmentControl : UserControl
    {
        public FileAttachmentControl()
        {
            this.InitializeComponent();
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }
}
