//<auto-generated/>

using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace GroupMeClient.AvaloniaUI.Views.Controls.Attachments
{
    public partial class FileAttachmentControl : UserControl
    {
        public FileAttachmentControl()
        {
            this.InitializeComponent();
        }
    }
}
