//<auto-generated />

using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace GroupMeClient.AvaloniaUI.Views.Controls.Attachments
{
    public partial class GroupMeImageAttachmentControl : UserControl
    {
        public GroupMeImageAttachmentControl()
        {
            this.InitializeComponent();
        }
    }
}
