//<auto-generated />

using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace GroupMeClient.AvaloniaUI.Views.Controls.Attachments
{
    public partial class ImageLinkAttachmentControl : UserControl
    {
        public ImageLinkAttachmentControl()
        {
            this.InitializeComponent();
        }
    }
}
