//<auto-generated />

using System.Windows.Controls;

namespace GroupMeClient.WpfUI.Views
{
    /// <summary>
    /// Interaction logic for LoginView.xaml.
    /// </summary>
    public partial class LoginView : UserControl
    {
        public LoginView()
        {
            this.InitializeComponent();
        }
    }
}
