//<auto-generated />

using System.Windows.Controls;

namespace GroupMeClient.WpfUI.Views
{
    /// <summary>
    /// Interaction logic for SearchView.xaml.
    /// </summary>
    public partial class SearchView : UserControl
    {
        public SearchView()
        {
            this.InitializeComponent();
        }
    }
}
