// <auto-generated />

using System;
using System.Windows.Controls;

namespace GroupMeClient.WpfUI.Views
{
    /// <summary>
    /// Interaction logic for WindowHost.xaml
    /// </summary>
    public partial class WindowHost : UserControl
    {
        public WindowHost()
        {
            InitializeComponent();
        }
    }
}
