//<auto-generated />
using System.Windows.Controls;

namespace GroupMeClient.WpfUI.Views.Controls.Attachments
{
    /// <summary>
    /// Interaction logic for GroupMeImageAttachmentControl.xaml
    /// </summary>
    public partial class GroupMeImageAttachmentControl : UserControl
    {
        public GroupMeImageAttachmentControl()
        {
            this.InitializeComponent();
        }
    }
}
