//<auto-generated/>

using System.Windows.Controls;

namespace GroupMeClient.Wpf.Notifications.Display.Win7
{
    /// <summary>
    /// Interaction logic for Win7ToastNotification.xaml
    /// </summary>
    public partial class Win7ToastNotification : UserControl
    {
        public Win7ToastNotification()
        {
            this.InitializeComponent();
        }
    }
}
