//<auto-generated/>

using System.Windows;

namespace GroupMeClient.WpfUI.Plugins.Views
{
    /// <summary>
    /// Interaction logic for ImageGalleryWindow.xaml
    /// </summary>
    public partial class ImageGalleryWindow : Window
    {
        public ImageGalleryWindow()
        {
            InitializeComponent();
        }
    }
}
